version: '3.9'

services:
    app:
        container_name: contacts-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/app/src
        ports:
            - '3000:3000'
        environment:
            - CHOKIDAR_USEPOLLING=true
            - SKIP_PREFLIGHT_CHECK=true
